# This is a basic workflow to help you get started with Actions

name: bump_version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
    
      - uses: yanamura/ios-bump-version@v1.7.0
        with:
          version: '1.1.0'
          build-number: '2'
