# This is a basic workflow to help you get started with Actions

name: bump_version

on:
  workflow_dispatch:
    inputs:
      version:
        description: new app version x.x.x.

jobs:
  versionup:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: yanamura/ios-bump-version@v1
      with:
        version: ${{ github.event.inputs.version }}
        build-number: ${{ github.run_number }}
        project-path: Sample/
    - name: update
      run: |
        git add .
        git commit -m "bump version"
        git push origin HEAD
